### PR TITLE
309 add icon

### LINKED ISSUE #309: Add GeriLife logo as app icon and favicon
We would like to add our product logo as a favicon and app icon. That way, users start to recognize the brand mark when bookmarking the site or adding an app launcher to their home screen.

# Task
Add the GeriLife logo in the following places:
- favicon
- app launcher (iOS and Android)
- navigation menu

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #309 

### Navigation menu (large& small screens)
joxi_screenshot_1548496929295
joxi_screenshot_1548496997814

## Quick launch icon (Android or iOS)
Add screenshot here showing Android or iOS emulator home screen launcher. E.g. launch Android emulator, visit localhost in browser, and create app shortcut (or some similar method). This does not require a Cordova build, or anything along those lines.

### CODE REVIEW

**Comment by brylie** [comment]
Great work! Could you provide a screenshot showing the App icon used as a shortcut in Android or iOS emulator?

**Comment by marla-singer** [comment]
@brylie Added screens of  iOS and Android home screens

**Comment by brylie** [comment]
@marla-singer Where are the screenshots of the iOS and Android home screens? Did you mean to edit the PR description, or are they somewhere else?

**Comment by marla-singer** [comment]
Yes, I've saved it
image
image

**Pull request merged**
