### PR TITLE
Meteor 1.8 update

### PR DESCRIPTION
**Pull request by brylie**
Update Meteor core, Meteor packages, and NPM packages to latest compatible versions.

### CODE REVIEW

**Comment by brylie** [comment]
@marla-singer please test the branch, if you have some spare time.

**Comment by brylie** [comment]
@shailee-m can you please take a look at this branch, to see if we can update to 1.8? There may be additional updates since this branch was last active.

**Comment by shailee-m** [comment]
> @shailee-m can you please take a look at this branch, to see if we can update to 1.8? There may be additional updates since this branch was last active.

@brylie: There is a meteor patch update and few libraries that need updating. These may not be required right away as the current version is also working just fine. 
Also I suggest we upgrade to latest babel/runtime@latest (i.e. v7.4.3) since the current version we are using in `develop` is a beta version.

**Comment by brylie** [comment]
OK, lets close this branch, since your Vue branch was just merged.

**Comment by brylie** [comment]
@shailee-m can you open a new branch to run the remaining updates?

**Pull request closed without merging**
