### PR TITLE
Replace Homes resident activity levels charts with consolidated charts

### LINKED ISSUE #323: Replace Homes resident activity levels charts with consolidated charts
The Homes screen shows resident activity level percentages using horizontal bar charts. The charts are taking up unnecessary space with:
- separate bars for each activity level (poor, moderate, excellent)
- separate x-axis for each home

current home activity levels

## Task
Consolidate Homes resident activity level percentages chart, so that:
- activity level categories are stacked horizontally
- all homes within a group share a common x-axis

screenshot from 2019-02-06 15-11-03

Use Plotly.js to create the new chart component.

## Server-side data processing
To the extent possible, data processing should be done on the server. Create a method that builds on the existing server methods, but returns a single data response *similar to*:

- home 1
    - activity levels
        - low: 20
        - medium: 60
        - high: 20
- home 2
    - activity levels
        - low: 40
        - medium: 20
        - high: 40

Of course, take into account how the charting library will want the data to be shaped, so there as little client-side data parsing as possible.

### PR DESCRIPTION
**Pull request by marla-singer**
Closes #323

### CODE REVIEW

**Comment by brylie** [comment]
On Firefox 65.0, the home charts are not rendering with the same width:

screenshot from 2019-02-16 11-32-47

This makes it difficult to compare homes, as the percentages do not line up. I.e. we should be able to scan our eyes vertically to see how the homes compare, as the red and green bars are primarily important.

**Comment by brylie** [comment]
When I refresh the browser, the bar lengths vary:

screenshot from 2019-02-16 11-47-23
screenshot from 2019-02-16 11-47-33
screenshot from 2019-02-16 11-47-43

**Comment by brylie** [comment]
It looks like this can be easily fixed by adding `responsive: true` to the `newPlot` configuration object:

https://plot.ly/javascript/configuration-options/#making-a-responsive-chart

**Comment by brylie** [comment]
Also, consider tweaking the chart right margin to `15` so that the 100% text doesn't get clipped.

**Comment by marla-singer** [comment]
@brylie Done

**Pull request merged**
