### PR TITLE
User group assignment

### LINKED ISSUE #338: Allow users to be assigned to groups
After discussing with Marjo, we agreed that users should be assigned to groups. That means that a user will see all homes and residents that belong to that group.

# Task
- [x] data model supports user group assignment
- [x] Users can be assigned to group(s) from Users page
- only related homes/residents are visible to user when
  - [x] viewing Homes page
  - [x] viewing Home Profile
- Only relevant residents visible to user on:
  - [x] add activity form
- Only show correct residents on data entry forms
  - [x] Add Activity
  - [x] Add Feeling
- [x] Activities page should show only activities from user-visible residents
- [x] Home Report page should show 'Not Authorized' when user visits without proper group membership
- [x] Residents page should show only user-visible residents
- [x] Activities page filters Resident select should show only relevant homes and residents
- [x] Admin user should be able to see all homes, residents, and residencies

### LINKED ISSUE #360: Fix repeated console error related to SCSS in node_modules dependency
For some reason, our project is trying to compile SCSS files in the `node_modules` directory. As a result, there are repeated errors in the browser console:

> node_modules/slim-select/src/docs/pages/home.vue:16  [vue-component] Error while compiling in tag <style> using lang scss: [33mCan't find handler for lang 'scss', did you install it?[39m

scss_console_errors

Figure out how to fix or suppress these errors, as they make it difficult to debug other issues.

### PR DESCRIPTION
**Pull request by brylie**
Closes #338 
Closes #360

### CODE REVIEW

**Comment by shailee-m** [comment]
Only relevant residents visible to user on - add activity form: Working fine
Tasks to reproduce:

1) Create a new user and give it one group (for example Onnela)
2) Go to activities> Add activity
Results:  The add resident drop down shows home/residents of the housegroup Onnela only

On homes page:
Results: Table for only one home group with a list of its houses is displayed

**Comment by shailee-m** [comment]
On dashboard> quick add tab> add activity/feelings, it is not retrieving the list of residents at all

**Comment by brylie** [comment]
Yes, *settings* should only be accessible by Admin users.

**Comment by brylie** [comment]
We should open a separate issue to ensure settings routes are onlu accessible by an admin.

**Comment by brylie** [comment]
@shailee-m can you please test this branch again? Specifically, check the Residents page and the 'departed' toggle on that page. It should only show residents visible to the user, and departed residents visible to the user when the toggle is enabled.

**Comment by brylie** [comment]
@shailee-m can you please do another round of QA on this branch? Specifically, check the following:

- [ ] data model supports user group assignment
- [  Users can be assigned to group(s) from Users page
- only related homes/residents are visible to user when
  - [ ] viewing Homes page
  - [ ] viewing Home Profile
- Only relevant residents visible to user on:
  - [ ] add activity form
- Only show correct residents on data entry forms
  - [ ] Add Activity
  - [ ] Add Feeling
- [ ] Activities page should show only activities from user-visible residents
- [ ] Home Report page should show 'Not Authorized' when user visits without proper group membership
- [ ] Residents page should show only user-visible residents
- [ ] Activities page filters Resident select should show only relevant homes and residents
- [ ] Admin user should be able to see all homes, residents, and residencies

**Comment by shailee-m** [comment]
@brylie  I tested the above list and almost  everything checks out for a non admin user. I just have two scenarios which look doubtful. 

By default an admin user should be able to see three groups: 
1. Onnela, 2. Tammela, 3. Puistola

I created a user and assigned the group `Onnela` to it. This has a list of 3 homes namely: Lilyan ton, South Jovany, Von chester.

1.When given admin rights to the new user:
- When no groups are assigned to user, they can see only `Onnela` and `Puistola`. But after assigning any one of the home groups, all the home groups become visible to the user.

2.Without admin rights: 
- Only the home `Onnela` was visible to the user.
- QuickAdd>AddFeelings is not retrieving all residents for some reason. The list of residents in the the `AddActivity` should be the same as that in `AddFeelings`. Some how the list of residents in the last home, in the dropdown, i.e.  `von chester` is empty.

**Comment by shailee-m** [comment]
> @shailee-m can you please test this branch again? Specifically, check the Residents page and the 'departed' toggle on that page. It should only show residents visible to the user, and departed residents visible to the user when the toggle is enabled.

Yes I tested this, it is working as expected

**Comment by shailee-m** [comment]
> Yes, _settings_ should only be accessible by Admin users.

Also, if one admin(Admin-A)  created another admin user(Admin-B), currently admin-B cannot deleted admin-A. Here we should also hide the `edit` button beside Admin-A, in Admin-B's login, as admin-B should not be able to remove admin rights of Admin-A

**Comment by brylie** [comment]
@shailee-m I made changes based on your feedback. Can you please review once more and add an approval, if things work as expected now?

**Pull request merged**
